import Head from "next/head";
import { useEffect,useState } from "react";
import { getServerSession } from "next-auth";
import { NextAuthOptions } from "../api/auth/[...nextauth]";


export default function OrgDashboard () {
    const [screenHeight,setScreenHeight] = useState(0);

    useEffect(()=>{
      setScreenHeight(window.innerHeight - 60)
    },[]);

    return (
        <>
        <Head>
        <title>Talent Profile Update | Company</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/realfast_logo.png" />
        </Head>
        <main className={styles.container} style={{minHeight:`${screenHeight}px`}}>
            <div className={styles.wrapper}>
                <h2 className={styles.title}>you are signed in as {session?.user.email} </h2>
            </div>
        </main>
        </>
    )
}

export async function  getServerSideProps (context) {
    const session = await getServerSession(context.req,context.res,NextAuthOptions);

    // if there is an active session, redirect talent dashboard
    if (session){
       if (session.user.accountType != 'org'){
        return{
            redirect:{
                destination:'/',
                permanent:false
            }
        }
       } 
    } else{
        return{
            redirect:{
                destination:'/signin',
                permanent:false
            }
        }
       }

    }


    return{
        props:{
            session:JSON.parse(JSON.stringify(session))
        }
    }


const styles ={
    container:'w-full flex flex-col justify-center items-center px-16',
    wrapper:'w-full md:w-[720px] basepy-8',
    title:'text-xl text-center mb-4',
  }