import Head from "next/head";
import { useEffect,useState } from "react";


export default function Dashboard () {
    const [screenHeight,setScreenHeight] = useState(0);

    useEffect(()=>{
      setScreenHeight(window.innerHeight - 60)
    },[]);

    return (
        <>
        <Head>
        <title>Talent Profile Update | Real Fast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/realfast_logo.png" />
        </Head>
        <main className={styles.container} style={{minHeight:`${screenHeight}px`}}>
            <div className={styles.wrapper}>
                <h2 className={styles.title}>you are signed in as {} </h2>
            </div>
        </main>
        </>
    )
}

const styles ={
    container:'w-full flex flex-col justify-center items-center px-16',
    wrapper:'w-full md:w-[720px] basepy-8',
    title:'text-xl text-center mb-4',
  }